language: node_js
node_js:
- '4.2'
env:
  global:
  - GH_REF=github.com/prose/prose.git
  - DEPLOY_BRANCH=master
  - secure: R+ZWJe6XOXit4QKOeQqlHw20k6CDuqDXEHo3SSkkdsEax+cWxIaKPv8C9zp+IA8SM32uz6DNkfo5wGUJ/HCUE/S3WZqlr7qijroshjsmcZPRx6+TxVRzE1Xp0iMbeGibSCFZGrWlJmYgHnq5rQAFtjiztNhkSmkhuq3d9nsg8xM=
cache:
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
before_script:
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
